services:
  qbittorrent:
    image: linuxserver/qbittorrent:libtorrentv1-version-release-5.0.3_v1.2.19
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - TORRENTING_PORT=59252
    volumes:
      - ./data/qbittorrent:/config
      - ./downloads:/downloads
    ports:
      - 59252:59252
      - 59252:59252/udp
      - 8080:8080

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    volumes:
      - ./data/prowlarr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    ports:
      - 9696:9696


  kanojo:
    image: plsy1/kanojo:latest
    container_name: kanojo
    restart: unless-stopped
    volumes:
      - ./data/kanojo:/app/backend/data
      - ./runtime:/app/runtime
    ports:
      - "12450:80"
    environment:
      - TZ=Asia/Shanghai